backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/homepage/index.md"
        label: "homepage"
        name: "Homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: "First Name", name: "firstName", widget: "string", default: "Hannah"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Last Name", name: "lastName", widget: "string", default: "Frishberg"}
          - {label: "Body", name: "body", widget: "markdown"}
